default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password:

development:
  <<: *default
  database: draft_machine_dev

test:
  <<: *default
  database: draft_machine_test

production:
  <<: *default
  database: draft_machine_prod
  username: draft_machine_db
  password:
